name: docker

on:
  push:
    branches: main
    paths:
      - 'api_gateway/**'
      
jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with: 
          context: ./api_gateway/
          file: ./api_gateway/Dockerfile
          push: true
          tags: rahilshah/bingbong:api_gateway